version: "3.8"
services:
  msgo:
    build: .
    environment:
      DB_HOST: db
    ports:
      - 3003:3003
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "msgo"
    ports:
      - 3306:3306

