version: "3.8"
services:
  msgo:
    build: .
    environment:
      DB_HOST: dbs
    ports:
      - 9000:3003
  dbs:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
